<a href="https://colab.research.google.com/github/safiyabegm/Python_basic/blob/main/Basic_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello, World!")

Hello, World!


**Python Indentation**
Indentation refers to the spaces at the beginning of a code line.

Where in other programming languages the indentation in code is for readability only, the indentation in Python is very important.

Python uses indentation to indicate a block of code.

In [ ]:
if 5 > 2:
 print("Five is greater than two!")

Five is greater than two!


In [ ]:
if 5 > 2:
print("Five is greater than two!")  

IndentationError: ignored

**Python Variables**
Python has no command for declaring a variable.

In [ ]:
x = 5
y = "Hello, World!"

In [ ]:
print(x)
print(y)

5
Hello, World!


**Python Data Types**
Python has the following data types built-in by default, in these categories:


1.   Text Type:	str
2.   Numeric Types:	int, float, complex
3.   Sequence Types:	list, tuple, range
4.   Mapping Type:	dict
5.   Set Types:	set, frozenset
6.   Boolean Type:	bool
7.   Binary Types:	bytes, bytearray, memoryview
8.   None Type:	NoneType

In [ ]:
x = 5
print(type(x))

In [ ]:
x = True
print(type(x))

x = ["apple", "banana", "cherry"]	list	
x = ("apple", "banana", "cherry")	tuple

In [ ]:
x = ["apple", "banana", "cherry"]	
x = ("apple", "banana", "cherry")	

**Setting the Specific Data Type**
use the following constructor functions
x = bytes(5)
x = dict(name="John", age=36)

Python Conditions and If **statements**
Python supports the usual logical conditions from mathematics:
1.   Equals: a == b
2.   Not Equals: a != b
3.   Less than: a < b
4.   Less than or equal to: a <= b
5.   Greater than: a > b
6.   Greater than or equal to: a >= b

*   These conditions can be used in several ways, most commonly in "if statements" and loops







In [ ]:
#Simple If Statement
a = 33
b = 200
if b > a:
  print("b is greater than a")

b is greater than a


In [ ]:
#If statement, without indentation (will raise an error):

a = 33
b = 200
if b > a:
print("b is greater than a") # you will get an error

IndentationError: ignored

In [ ]:
#The elif keyword is Python's way of saying "if the previous conditions were not true, then try this condition".

a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a and b are equal


In [ ]:
#The else keyword catches anything which isn't caught by the preceding conditions.
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b


In [ ]:
#Short Hand If
if a > b: print("a is greater than b")


a is greater than b


In [ ]:
#Short Hand If ... Else
a = 2
b = 330
print("A") if a > b else print("B")

B


Python Loops




*   Python has two primitive loop commands:
*   while loops
*   for loops

In [ ]:
#The while Loop
#With the while loop we can execute a set of statements as long as a condition is true.
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [ ]:
#The break Statement
#With the break statement we can stop the loop even if the while condition is true:
#Exit the loop when i is 3:

i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3


In [ ]:
#The continue Statement
#With the continue statement we can stop the current iteration, and continue with the next:
#Continue to the next iteration if i is 3:

i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6


In [ ]:
#Python For LoopsA for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).

#This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-orientated programming languages.

#With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.
#Print each fruit in a fruit list:

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


In [ ]:
NumPy Tutorial

**NumPy Tutorial**

1.   NumPy is a Python library.
2.   NumPy is used for working with arrays
3.   NumPy is short for "Numerical Python".


*   Why Use NumPy?      
*  Lists that serve the purpose of arrays, but they are slow to process.
*  NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

1.   The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
2.   Arrays are very frequently used in data science, where speed and resources are very important











# **Why is NumPy Faster Than Lists?**

*   NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
*   This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# *   Which Language is NumPy written in? 
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++
*   List item










Installation of NumPy
C:\Users\Your Name>pip install numpy

In [ ]:
#ExampleGet your own Python Server
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

In [ ]:
import numpy as np

print(np.__version__)

Create a NumPy ndarray Object

*   NumPy is used to work with arrays. The array object in NumPy is called ndarray.
*   List item



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Arrays

*   A dimension in arrays is one level of array depth (nested arrays).
*   List item



In [ ]:
#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
#Higher Dimensional Arrays
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

In [ ]:
#Negative Indexing
#Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
#NumPy Array Slicing
#Slicing arrays
#Slicing in python means taking elements from one given index to another given index.
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


PYTHON FOR DATA SCIENCE
Pandas DataFrame :

*   Creating a DataFrame

*   Dealing with Rows and Columns
*   Indexing and Selecting Data

*   Working with Missing Data
*   Iterating over rows and columns


In [ ]:
#Creating a dataframe using List: DataFrame can be created using a single list or a list of lists.

# import pandas as pd
import pandas as pd
 
# list of strings
lst = ['DATASCIENE', 'IS ', 'POWERFUL', 'TOPIC', 
            'TO', 'AUTOMATE', 'WORLD']
 
# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
print(df)


            0
0  DATASCIENE
1         IS 
2    POWERFUL
3       TOPIC
4          TO
5    AUTOMATE
6       WORLD


In [ ]:
# Python code demonstrate creating 
# DataFrame from dict narray / lists 
# By default addresses.
 
import pandas as pd
 
# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
#Column Selection: In Order to select a column in Pandas DataFrame, we can either access the columns by calling them by their columns name.

# Import pandas package
import pandas as pd
 
# Define a dictionary containing employee data
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
 
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)
 
# select two columns
print(df[['Name', 'Age']])

     Name  Age
0     Jai   27
1  Princi   24
2  Gaurav   22
3    Anuj   32


In [ ]:
# importing pandas package
import pandas as pd
 
# making data frame from csv file
data = pd.read_csv("nba.csv", index_col ="Name")
 
# retrieving row by loc method
first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]
 
 
print(first, "\n\n\n", second)

FileNotFoundError: ignored

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:

import pandas as pd
pd.read_csv('/content/drive/MyDrive/Colab Notebooks/nba.csv')

Name            Team  Number Position  Age  Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25  06-Feb     180   
1      Jae Crowder  Boston Celtics      99       SF   25  06-Jun     235   
2     John Holland  Boston Celtics      30       SG   27  06-May     205   
3      R.J. Hunter  Boston Celtics      28       SG   22  06-May     185   
4    Jonas Jerebko  Boston Celtics       8       PF   29  06-Oct     231   
..             ...             ...     ...      ...  ...     ...     ...   
452     Trey Lyles       Utah Jazz      41       PF   20  06-Oct     234   
453   Shelvin Mack       Utah Jazz       8       PG   26  06-Mar     203   
454      Raul Neto       Utah Jazz      25       PG   24  06-Jan     179   
455   Tibor Pleiss       Utah Jazz      21        C   26  07-Mar     256   
456    Jeff Withey       Utah Jazz      24        C   26     7-0     231   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
452           Kentucky  2239800.0  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  

[457 rows x 9 columns]